name: Trigger
on: [push]

jobs:
  triggering-dispatch:
    runs-on: windows-latest
    steps:
      - name: Script trigger
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.repos.createDispatchEvent({
              owner: "DonPug",
              repo: "gh-worker",
              event_type: "my-event",
            });
