name: Trigger
on: [push]

jobs:
  triggering-dispatch:
    runs-on: windows-latest
    steps:
      - name: Script trigger
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: "gh-worker",
              event_type: "my-event",
            });
