name: Trigger
on: [push]

jobs:
  triggering-dispatch:
    runs-on: windows-latest
    steps:
      - name: Script trigger
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              DonPug,
              gh-worker,
              my-event,
            });
